language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
script:
  - git config --global user.name "${U_NAME}"
  - git config --global user.email "${U_EMAIL}"
  - git clone "https://${GH_TOKEN}@${GH_REF}"
  - if [! -d "${GH_DIR}"]; then
  - mkdir "${GH_DIR}"
  - fi
  - cp -rf storybook-static/* "${GH_DIR}"
  - cd ./yolkpie.github.io
  - git add .
  - git commit -m 'travis-ci auto build components-vue'
  - git push origin "${P_BRANCH}"
branches:
  only:
    - master