language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build-storybook
after_success:
  - git config --global user.name "${U_NAME}"
  - git config --global user.email "${U_EMAIL}"
  - git clone "https://${GH_TOKEN}@github.com/YolkPie/components-vue.git"
  - if [! -d components-vue/storybook-static]; then
  - mkdir components-vue/storybook-static
  - fi
  - cp -rf storybook-static/* components-vue/storybook-static
  - cd ./components-vue
  - git add .
  - git status
  - git commit -m 'travis-ci auto build components-vue'
  - git push origin master
  - git push origin `git subtree split --prefix=storybook-static master`:gh-pages --force

  - cd ../
  - git clone "https://${U_NAME2}:${CO_TOKEN}@e.coding.net/yolkpie/components/components.git"
  - if [! -d components/storybook-static]; then
  - mkdir components/storybook-static
  - fi
  - cp -rf storybook-static/* components/storybook-static
  - cd ./components
  - git add .
  - git commit -m 'travis-ci auto build components'
  - git push origin master
branches:
  only:
    - master
